variable "REGISTRY" {
  default = "ghcr.io/imu-iccs"
}

# Exact digests resolved at build time by the preflight job - see workflow.
# Falling back to a floating tag only matters for local/manual builds.
variable "CORE_SERVER_REF" {
  default = "ghcr.io/imu-iccs/ems-server:8.0.0-snapshot"
}

variable "CORE_BUILDER_REF" {
  default = "ghcr.io/imu-iccs/ems-server-core-builder:8.0.0-snapshot"
}

variable "BANNER_IMAGE" {
  default = "na"
}

variable "BANNER_DESCR" {
  default = ""
}

variable "COMMIT_SHA" {
  default = "unknown-sha"
}

# variable "COMMIT_SAFE_TIME" {
#   default = "unknown-time"
# }

# Single platform per bake invocation - set per matrix leg in CI
variable "PLATFORM" {
  default = "linux/amd64"
}

variable "ARCH_TAG" {
  default = "amd64"
}


group "default" {
  targets = ["plugin"]
}

target "plugin" {
  context    = "ems-nebulous-translator"
  dockerfile = "Dockerfile"
  target     = "ems-server-with-nebulous-translator"

  platforms = [PLATFORM]

  # docker-image:// contexts resolve the correct per-platform manifest
  # automatically, even from a manifest-list ref - no arch suffix needed.
  contexts = {
    ems_core_builder_image = "docker-image://${CORE_BUILDER_REF}"
    ems_core_image         = "docker-image://${CORE_SERVER_REF}"
  }

  args = {
    DOCKER_IMAGE = "${BANNER_IMAGE}"
    BUILD_DESCR  = "${BANNER_DESCR}Plugin generated by GitHub CI"
  }

  cache-from = ["type=gha,scope=ems-nebulous-${ARCH_TAG}"]
  cache-to   = ["type=gha,scope=ems-nebulous-${ARCH_TAG},mode=max"]

  tags = [
    "${REGISTRY}/ems-server-nebulous:${COMMIT_SHA}-${ARCH_TAG}",
  ]
}
